/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/types.h>


#define REM_INST ((u_long)100)
#define REM_INST_VERS ((u_long)1)
#define INSTALL ((u_long)1)
extern int *install_1();
