#	$made/applications/feline/main/Makefile
#
#	M J Wooldridge
#
#	Sets up links, etc.

all	:
	-ln -s ../initial/initial.p
	-ln -s ../blood/blood.p
	-ln -s ../haemolytic/haemolytic.p
	-ln -s ../haemorrhagic/haemorrhagic.p
	-ln -s ../aplasia/aplasia.p

cleanup	:
	-rm *% *- core dkbs.trace

