
/*
 * mascgenc.c
 * 
 * M J Wooldridge 
 * February 1990
 * 
 * Generate the C program to instantiate the defined system.
 */

/* first the usual #includes */

#include<stdio.h>

#include	"../include/hosts.h"
#include	"../include/cosmetic.h"
#include	"masc.h"

/* External Data Declarations */

extern	AG
* agent_list;

extern	int
cflag,
vflag,
sflag,
opt_use_mp,
opt_trace,
opt_dkbs,
opt_reader,
opt_sunview,
opt_debugger,
opt_wintool;

extern	char
* pre_file,
*rpc_include_file,
*paths_file,
*sym_tab[],
time_string[],
*stralloc();

extern	void
debug(),
masc_error(),
fatal();

/* Table Functions */

/* strwhere() returns the posn of s in t[] else -1 */

int 
strwhere(t, m, s)
	char           *t[], *s;
	int             m;
{
	int             i = 0, where = -1;

	while ((i < m) AND(where == -1))
		if (strcmp(t[i], s) == 0)
			where = i;
		else
			i++;
	return (where);
}

/* strisin() returns TRUE if s is in table t[] */

int 
strisin(t, m, s)
	char           *t[], *s;
	int             m;
{
	if (strwhere(t, m, s) != -1)
		return (TRUE);
	else
		return (FALSE);
}

/* strinsert() inserts a string into a table */

int 
strinsert(t, m, s)
	char           *t[], *s;
	int            *m;	/* note a POINTER this time */
{
	int             i = 0, flag = FALSE;

	while ((i < (*m)) AND (!flag))
		if (strcmp(t[i], s) == 0)
			flag = TRUE;
		else
			i++;
	if (!flag) {
		t[(*m)] = s;
		(*m)++;
		return ((*m) - 1);
	} else
		return (i);
}

/* the code generation routines */

/* write headings is a utility used for all generated files */

void
write_headings(ofname, of)
	char           *ofname;
	FILE           *of;
{
	fprintf(of, "\n/*\t%s\n *\n *\tGenerated by masc\n", ofname);
	fprintf(of, " *\tAt %s *\tDo NOT Edit!\n */\n\n", time_string);
}

/* now the C code generation functions */
/* copy preamble copies the generic preamble from pre_file */

void
copy_preamble(ofname, of)
	char           *ofname;
	FILE           *of;
{
	FILE           *prefile;
	int             buf;

	if ((prefile = fopen(pre_file, "r")) == null(FILE))
		fatal("Couldn't open preamble file `%s'\n", pre_file);

	fflush(of);
	while (NOT feof(prefile)) {
		buf = fgetc(prefile);
		if (NOT feof(prefile))
			fputc(buf, of);
	}
	fflush(of);
	fclose(prefile);
}

void
create_go_file(name)
	char           *name;
{
	FILE           *gofile;
	char		tmp[100];

	sprintf(tmp, "go%s.go", name);
	if ((gofile = fopen(tmp, "w")) == null(FILE))
		fatal("Couldn't open go file");
	fprintf(gofile, "consult(%s).\n", name);
	fclose(gofile);
}

/* create the global declarations */

void 
create_default_values(ofname, of)
{
	int             count = 0;

	fprintf(of, "\n\n#include\t<stdio.h>\n");
	fprintf(of, "#include\t<signal.h>\n");
	fprintf(of, "#include\t<rpc/rpc.h>\n");
	fprintf(of, "#include\t\"%s\"\n", rpc_include_file);
	fprintf(of, "#include\t\"%s\"\n", paths_file);
	
	fprintf(of, "\n\t/* default values */\n\n");
	fprintf(of, "#define\tDEFAULT_DFLAG\t%d\n", opt_dkbs);
	fprintf(of, "#define\tDEFAULT_READER\t%d\n", opt_reader);
	fprintf(of, "#define\tDEFAULT_SUNVIEW\t%d\n", opt_sunview);
	fprintf(of, "#define\tDEFAULT_AWT\t%d\n", opt_wintool);
	fprintf(of, "#define\tDEFAULT_DEBUGGER\t%d\n", opt_debugger);

	fprintf(of, "\n\n\t/* now the remote hosts */\n\n");
	fprintf(of, "char\t*host_tab[] = {\n");
	while (hosts[count] != null(char))
		fprintf(of, "\t\"%s\",\n", hosts[count++]);
	fprintf(of, "\t(char *)0\n};\n\n");
	fprintf(of, "int\tnum_hosts\t= %d;\n\n", count);
}

/* create the install_called2() function */

void
create_install_called2(ofname, of)
	char           *ofname;
	FILE           *of;
{

	AG             *ag;

	fprintf(of, "\n\t/* install only those agents that should be on this machine */\n\n");

	fprintf(of, "void\tinstall_called2()\n{\n");
	ag = agent_list;
	while (ag != null(AG)) {
		fprintf(of, "\n\n\t/* now the agent %s */\n\n", sym_tab[ag->name]);
		fprintf(of, "\tif(strcmp(hostname,\"%s\") == 0) /* then install this agent */\n", sym_tab[ag->host]);
		fprintf(of, "\t{\n\t\tpid[pcount] = fork();\n");
		fprintf(of, "\t\tif(pid[pcount++] == 0)\t/* then child */\n");
		fprintf(of, "\t\t{\n");
		fprintf(of,
		      "\t\t\tfprintf(stderr,\"%s : initiating %s.\\n\");\n",
			SYSTEM_NAME, sym_tab[ag->name]);

		switch (ag->language) {

		case LANGUAGE_PWMPOP11:
			{
				fprintf(of,
				    "\t\t\texeclp(EXEC_PWM, \"pwmtool\", ");
				fprintf(of,
					"\"-Wp\" , \"0\", \"0\", \"-Wh\" , \"25\" , \"-Ww\", \"80\" ,\"pop11\", \"%s\", (char *)0);\n",
					sym_tab[ag->name]);
			}
			break;

		case LANGUAGE_DEFAULT:
		case LANGUAGE_POP11:
			{
				fprintf(of,
					"\t\t\texeclp(EXEC_POP,\"pop11\", \"%s\", (char *)0);\n",
					sym_tab[ag->name]);
			}
			break;

		case LANGUAGE_LISP:
			{

				/*
				 * first write the bit of code to redirect
				 * stdin
				 */

				fprintf(of,
					"\t\t\tif((infile = freopen(\"%s.lsp\",\"r\",stdin)) == (FILE *)0)\n",
					sym_tab[ag->name]);

				fprintf(of,
					"\t\t\t{\n");
				fprintf(of,
					"\t\t\t\tfprintf(stderr,\"couldn't reallocate stdin\\n\");\n");

				fprintf(of,
					"\t\t\t\texit(1);\n");
				fprintf(of,
					"\t\t}\n");

				fprintf(of,
					"\t\t\texeclp(EXEC_LISP,\"lisp\",(char *)0);\n");
			}
			break;

		case LANGUAGE_C:
			{
				fprintf(of,"\t\t\texeclp(\"%s\",\"%s\",(char *)0);\n", sym_tab[ag->name]);
			}
			break;		

		case LANGUAGE_PROLOG:
			{
				create_go_file(sym_tab[ag->name]);

				/*
				 * TO DO :- change this so it re-directs
				 * stdin
				 */

				fprintf(of,
					"\t\t\tsystem(\"prolog <go%s.go\");\n", sym_tab[ag->name]);
				fprintf(of, "\t\t\texit(1);\n");
			}
			break;

		default:
			fatal("internal error -- illegal language");
		}

		/* now the bit of code to finish off */

		fprintf(of,
			"\t\t\tfprintf(stderr,\"%s stopped\\n\");\n", sym_tab[ag->name]);
		fprintf(of,
			"\t\t\texit(1);\n");

		fprintf(of, "\t\t}\n\n");
		fprintf(of, "\t\tsleep(25);\n");
		fprintf(of, "\t}\n");

		/* now move onto the next agent */

		ag = (ag->next);
	}
	fprintf(of, "\n\twait_for_child_death();\n");
	fprintf(of, "}\n\n");
}

/* creates the install_locally() function */

void
create_install_locally(ofname, of)
	char           *ofname;
	FILE           *of;
{

	AG             *ag;

	/* print out the function header */

	fprintf(of, "\n\t/* installs the system on the local machine */\n\n");
	fprintf(of, "void\tinstall_locally()\n{\n");
	fprintf(of, "\tinstall_dkbs_locally();\n");
	fprintf(of, "\tsleep(10);\n");
	fprintf(of, "\tinstall_debugger_locally();\n");
	fprintf(of, "\tinstall_reader_locally();\n");
	fprintf(of, "\tinstall_wintool_locally();\n");
	fprintf(of, "\n\t/* now install remainder of agents */\n\n");


	ag = agent_list;
	while (ag != null(AG)) {
		fprintf(of, "\n\t/* now the agent %s */\n\n", sym_tab[ag->name]);
		fprintf(of, "\tpid[pcount] = fork();\n");
		fprintf(of, "\tif(pid[pcount++] == 0)\t/* then child */\n");
		fprintf(of, "\t{\n");
		fprintf(of,
			"\t\tfprintf(stderr,\"%s : initiating %s.\\n\");\n",
			SYSTEM_NAME, sym_tab[ag->name]);

		switch (ag->language) {

		case LANGUAGE_PWMPOP11:
			{
				fprintf(of,
				      "\t\texeclp(EXEC_PWM, \"pwmtool\", ");
				fprintf(of,
					"\"-Wp\" , \"0\", \"0\", \"-Wh\" , \"25\" , \"-Ww\", \"80\" ,\"pop11\", \"%s\", (char *)0);\n",
					sym_tab[ag->name]);
			}
			break;

		case LANGUAGE_DEFAULT:
		case LANGUAGE_POP11:
			{
				fprintf(of,
					"\t\texeclp(EXEC_POP,\"pop11\", \"%s\", (char *)0);\n",
					sym_tab[ag->name]);
			}
			break;

		case LANGUAGE_LISP:
			{

				/*
				 * first write the bit of code to redirect
				 * stdin
				 */

				fprintf(of,
					"\t\tif((infile = freopen(\"%s.lsp\",\"r\",stdin)) == (FILE *)0)\n",
					sym_tab[ag->name]);

				fprintf(of,
					"\t\t{\n");
				fprintf(of,
					"\t\t\tfprintf(stderr,\"couldn't reallocate stdin\\n\");\n");

				fprintf(of,
					"\t\t\texit(1);\n");
				fprintf(of,
					"\t\t}\n");

				fprintf(of,
					"\t\texeclp(EXEC_LISP,\"lisp\",(char *)0);\n");
			}
			break;

		case LANGUAGE_PROLOG:
			{
				create_go_file(sym_tab[ag->name]);

				/*
				 * TO DO :- change this so it re-directs
				 * stdin
				 */

				fprintf(of,
					"\t\tsystem(\"prolog <go%s.go\");\n", sym_tab[ag->name]);
				fprintf(of, "\t\texit(1);\n");
			}
			break;

		default:
			fatal("internal error -- illegal language");
		}

		/* now the bit of code to finish off */

		fprintf(of,
			"\t\tfprintf(stderr,\"%s stopped\\n\");\n", sym_tab[ag->name]);
		fprintf(of, "\t\texit(1);\n");

		fprintf(of, "\t}\n\n");
		fprintf(of, "\tsleep(25);\n");

		/* now move onto the next agent */

		ag = (ag->next);
	}

	/* now just tidy up */

	fprintf(of, "\n\n\twait_for_child_death();\n}\n");
}

/* the create body funtion creates the four main functions */

void 
create_body(ofn, off)
	char           *ofn;
	FILE           *off;
{
	create_install_locally(ofn, off);
	create_install_called2(ofn, off);
}

/* now tie it all together */

void
generate_dot_c_file()
{
	char	tmp[100],
		*ofname;
	FILE           *of;

	/* get dot c file name */

	sprintf(tmp, "%s.c", sym_tab[0]);
	ofname = stralloc(tmp);

	/* open .c file for writing */

	if ((of = fopen(ofname, "w")) == null(FILE))
		fatal("Couldn't open dot c file");

	/* now write headings */

	write_headings(ofname, of);

	/* create default values */

	create_default_values(ofname, of);

	/* copy preamble */

	copy_preamble(ofname, of);

	/* create the body */

	create_body(ofname, of);

	if (cflag) {
		int             pid;

		if (vflag)
			fprintf(stderr, "Phase Three : Compilation\n");

		if ((pid = fork()) < 0)
			fatal("fork failed");
		else if (pid == 0) {
			fclose(of);
			execlp("/bin/cc",
			       "cc",
			       ofname,
			       "-o",
			       sym_tab[0],
			"/home/warner/staff/mikew/made1.0/masc/rpcs/rem_inst_clnt.o",
			       (char *) 0);
		} else
			wait((int *) 0);
	}
}

/* THE END */
