#	Makefile for .../dkb-1.0/docs/...
#
#	M J Wooldridge
#	January 1990
#
#	Generates documentation for the `dkb' system using the -man macro
#	package. Type :-
#		make		For troff(1) formatted documents in man.tr
#		make pr		For text file in man.tx


