/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REM_DKB_H_RPCGEN
#define _REM_DKB_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define REM_DKB ((rpc_uint)99)
#define REM_DKB_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define FORWARD ((rpc_uint)1)
extern "C" int * forward_1(char **, CLIENT *);
extern "C" int * forward_1_svc(char **, struct svc_req *);

#elif __STDC__
#define FORWARD ((rpc_uint)1)
extern  int * forward_1(char **, CLIENT *);
extern  int * forward_1_svc(char **, struct svc_req *);

#else /* Old Style C */
#define FORWARD ((rpc_uint)1)
extern  int * forward_1();
extern  int * forward_1_svc();
#endif /* Old Style C */

#endif /* !_REM_DKB_H_RPCGEN */
