
;;;	haemolytic_model.p
;;;	generated from haemolytic_model.mp at Fri Nov  2 13:15:36 1990
;;;
;;;	This is POP11 Source - Do NOT Edit!


;;;	Operations to manipulate agent models

;;;     models.p
;;;
;;;     M J Wooldridge
;;;     December 1990
;;;
;;;     This file contains functions to manipulate POP-11 agent models. The
;;; models are assumed to be in the same form as that generated by the mp(3)
;;; agent model compiler program, run with the -pop11 option.

;;; First the system variables to hold the various details.

vars
    myinterests
    ainterests
    agent_name
    myskills
    askills
    acquaintances
    ;

;;; name(...) assigns it's argument to the system variable agent_name if the
;;; argument is a valid system name.

define  name(arg) -> retval;
    arg -> agent_name;
    isword(arg) -> retval;
enddefine;

;;; skills(...) allows the modelling of agent skills.

define  skills(ag,slist);

    if (ag = agent_name) then                       ;;; modelling agent
        slist -> myskills;
    elseif isundef(askills) then
        [[^ag ^slist]] -> askills;
    else
        askills <> [[^ag ^slist]] -> askills;
    endif;

enddefine;

;;; acquaintance(...) defines an agent to be the acquaintance ofthe
;;; modelling agent. Note that this differs slightly from the PROLOG
;;;  acquaintance definition, in that in the PROLOG acquaintance definition
;;; arbitrary relationships are possible.

define  acquaintance(ag);

    if isundef(acquaintances) then
        [ ^ag ] -> acquaintances;
    else
        acquaintances <> [ ^ag ] -> acquaintances;
    endif;

enddefine;

;;; local(...) returns `true' if its argument is known by the modelling agent.

define  local(fact) -> retval;

    member(fact,myskills) -> retval;

enddefine;

;;; remote(...) returns true if the fact passed as an argument is known by
;;; any agent other than the modelling agent.

define  remote(fact) -> retval;

    vars    skill;

    false -> retval;
    for skill in askills do
        if member(fact, hd(tl(skill))) then
            true -> retval;
        endif;
    endfor;

enddefine;

;;; get_agent_who_knows(...) returns the name of the agent who knows
;;; the fact passed as the argument. If the fact is knon locally then `false'
;;; is returned. If no-one knows he fact then `false' is also returned. You
;;; should always check for this condition.

define  get_agent_who_knows(fact) -> retval;

    vars    skill;

    if local(fact) then
        false -> retval;
    else
        false -> retval;
        for skill in askills do
            if member(fact, hd(tl(skill))) then
                hd(skill) -> retval;
            endif;
        endfor;
    endif;

enddefine;

;;;     interests(...) declares the interests of an agent

define  interests(ag,ilist);

    if(ag = agent_name) then
        ilist -> myinterests;
    elseif isundef(ainterests) then
        [[ ^ag ^ilist]] -> ainterests;
    else
        ainterests<>[[^ag ^ilist]] -> ainterests;
    endif;

enddefine;

;;;     who_is_interested(...) returns the list of agents interested in the
;;; argument. Returns [] if none.

define  who_is_interested(int) -> retval;

    vars retval interest ilist tmp;

    false -> retval;
    [] -> ilist;
    for interest in ainterests do
        if member(int, hd(tl(interest))) then
            hd(interest) -> tmp;
            ilist<> [ ^tmp ] -> ilist;
        endif;
    endfor;
    if length(ilist) > 0 then
        ilist -> retval;
    endif;

enddefine;

;;;	The Modelling Agent

name("haemolytic");
skills("haemolytic" , [ nothing ]);
interests("haemolytic" , []);


;;;	Acquaintances of the modelling agent

acquaintance("initial");
skills("initial" , [ appetite  lethargy  weakness  duration  respiration  haemic_murmur  colour  abdomen  heart_rate  pulse_character  weight ]);

interests("initial" , []);

;;;	End of agent models.

;;;	The Program Body


	;;; ntohing yet

;;;	The End.
