
;;;	user.p
;;;	generated from user.mp at Wed Jan 30 10:55:19 1991
;;;
;;;	This is POP11 Source - Do NOT Edit!


;;;	Operations to manipulate agent models

;;;     models.p
;;;
;;;     M J Wooldridge
;;;     December 1990
;;;
;;;     This file contains functions to manipulate POP-11 agent models. The
;;; models are assumed to be in the same form as that generated by the mp(3)
;;; agent model compiler program, run with the -pop11 option.

;;; First the system variables to hold the various details.

vars
    myinterests
    ainterests
    agent_name
    myskills
    askills
    acquaintances
    ;

;;; name(...) assigns it's argument to the system variable agent_name if the
;;; argument is a valid system name.

define  name(arg) -> retval;
    arg -> agent_name;
    isword(arg) -> retval;
enddefine;

;;; skills(...) allows the modelling of agent skills.

define  skills(ag,slist);

    if (ag = agent_name) then                       ;;; modelling agent
        slist -> myskills;
    elseif isundef(askills) then
        [[^ag ^slist]] -> askills;
    else
        askills <> [[^ag ^slist]] -> askills;
    endif;

enddefine;

;;; acquaintance(...) defines an agent to be the acquaintance ofthe
;;; modelling agent. Note that this differs slightly from the PROLOG
;;;  acquaintance definition, in that in the PROLOG acquaintance definition
;;; arbitrary relationships are possible.

define  acquaintance(ag);

    if isundef(acquaintances) then
        [ ^ag ] -> acquaintances;
    else
        acquaintances <> [ ^ag ] -> acquaintances;
    endif;

enddefine;

;;; local(...) returns `true' if its argument is known by the modelling agent.

define  local(fact) -> retval;

    member(fact,myskills) -> retval;

enddefine;

;;; remote(...) returns true if the fact passed as an argument is known by
;;; any agent other than the modelling agent.

define  remote(fact) -> retval;

    vars    skill;

    false -> retval;
    for skill in askills do
        if member(fact, hd(tl(skill))) then
            true -> retval;
        endif;
    endfor;

enddefine;

;;; get_agent_who_knows(...) returns the name of the agent who knows
;;; the fact passed as the argument. If the fact is knon locally then `false'
;;; is returned. If no-one knows he fact then `false' is also returned. You
;;; should always check for this condition.

define  get_agent_who_knows(fact) -> retval;

    vars    skill;

    if local(fact) then
        false -> retval;
    else
        false -> retval;
        for skill in askills do
            if member(fact, hd(tl(skill))) then
                hd(skill) -> retval;
            endif;
        endfor;
    endif;

enddefine;

;;;     interests(...) declares the interests of an agent

define  interests(ag,ilist);

    if(ag = agent_name) then
        ilist -> myinterests;
    elseif isundef(ainterests) then
        [[ ^ag ^ilist]] -> ainterests;
    else
        ainterests<>[[^ag ^ilist]] -> ainterests;
    endif;

enddefine;

;;;     who_is_interested(...) returns the list of agents interested in the
;;; argument. Returns [] if none.

define  who_is_interested(int) -> retval;

    vars retval interest ilist tmp;

    false -> retval;
    [] -> ilist;
    for interest in ainterests do
        if member(int, hd(tl(interest))) then
            hd(interest) -> tmp;
            ilist<> [ ^tmp ] -> ilist;
        endif;
    endfor;
    if length(ilist) > 0 then
        ilist -> retval;
    endif;

enddefine;

;;;	The Modelling Agent

name("user");
skills("user" , [ ostrich  penguin  albatross  zebra  giraffe  tiger  cheetah ]);
interests("user" , []);


;;;	Acquaintances of the modelling agent

acquaintance("carnivores");
skills("carnivores" , [ is_carnivore ]);

interests("carnivores" , []);

acquaintance("birds");
skills("birds" , [ is_bird  flies ]);

interests("birds" , []);

;;;	End of agent models.

;;;	The Program Body



;;; load code libraries

load basic_comms.p
load shell.p

;;; Rules

rule(
[cheetah
    [and
        is_carnivore
        dark_spots
    ]
]);

rule(
[albatross
    [and
        is_bird
        flies_well
    ]
]);

rule(
[penguin
    [and
        is_bird
        swims
        [not flies]
    ]
]);

rule(
[ostrich
    [and
        is_bird
        [not flies]
        long
    ]
]);

rule(
[zebra
    [and
        ungulate
        black_stripes
    ]
]);

rule(
[giraffe
    [and
        ungulate
        long
    ]
]);

rule(
[tiger
    [and
        is_carnivore
        black_stripes
    ]
]);

rule(
[ungulate
    [and
        mammal
        chews_cud
    ]
]);

rule(
[mammal
    [or
        gives_milk
        has_hair
    ]
]);

;;; Meta-Rules

metarule(
[fostrich ostrich 
	[ 
		[ print
			['The animal is an Ostrich']
		]
		[ quit ]
	]
]
);

metarule(
[fpenguin penguin 
	[
		[ print 
			['The animal is a Penguin']
		]
		[quit]
	]
]
);

metarule(
[falbatross albatross 
	[
		[ print 
			['The animal was an Albatross']
		]
		[quit]
	]
]
);

metarule(
[fzebra zebra 
	[
		[print
			['The animal was a Zebra']
		]
		[quit]
	]
]
);

metarule(
[fgiraffe giraffe 
	[
		[print 
			['The animal was a Giraffe']
		]
		[quit]
	]
]
);

metarule(
[ftiger tiger 
	[
		[print
			['The animal was a Tiger']
		]
		[quit]
	]
]
);

metarule(
[fcheetah cheetah 
	[
		[print
			['The animal was a cheetah']
		]
		[quit]
	]
]
);

;;; Questions

question(
[has_hair  'Does the animal have hair']);

question(
[gives_milk 'Does the animal give milk']);

question(
[flies_well	'Does the animal fly well']);

question(
[hoofs 'Does the animal have hoofs']);

question(
[chews_cud 'Does the animal chew the cud']);

question(
[tawny 'Is the animal a tawny (light brown) colour']);

question(
[dark_spots 'Is the animal covered in dark spots']);

question(
[black_stripes 'Is the animal covered in black stripes']);

question(
[long 'Does the animal have long legs AND a long neck']);

question(
[swims 'Can the animal swim']);

question(
[another_go 'Do you want another go?']);

;;;	Now set up the various environement variables

MIXED_MODE	-> strategy;
DISTRIBUTED	-> operation_mode;
WINDOW		-> terminal_mode;

;;; Now the startup

define startup();

    my_pr('\n\t\t\t   The Animals Database');
    my_pr('\n\t\t\t   --------------------\n\n');
    my_pr('Please answer the following questions...\n');

    investigate(
    [
        tiger
        penguin
        albatross
        zebra
        ostrich
        giraffe
        cheetah
    ]);

    my_pr('\n\t** Sorry, I couldnt guess it.\n');

enddefine;

define  begin();

    vars flag each dummy;

    true -> flag;

    pop11_register("user");

    while flag do

        startup();
        if evaluate("another_go") then
            clear();
            for each in acquaintances do
                pop11_request(each,"restart") -> dummy;
            endfor;
        else
            false -> flag;
        endif;
    endwhile;

enddefine;

begin();

;;;	The End.
